/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.translator.database.jooq;


import eu.dissco.core.translator.database.jooq.tables.DataMapping;
import eu.dissco.core.translator.database.jooq.tables.SourceSystem;
import eu.dissco.core.translator.database.jooq.tables.TranslatorJobRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.data_mapping</code>.
     */
    public final DataMapping DATA_MAPPING = DataMapping.DATA_MAPPING;

    /**
     * The table <code>public.source_system</code>.
     */
    public final SourceSystem SOURCE_SYSTEM = SourceSystem.SOURCE_SYSTEM;

    /**
     * The table <code>public.translator_job_record</code>.
     */
    public final TranslatorJobRecord TRANSLATOR_JOB_RECORD = TranslatorJobRecord.TRANSLATOR_JOB_RECORD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DataMapping.DATA_MAPPING,
            SourceSystem.SOURCE_SYSTEM,
            TranslatorJobRecord.TRANSLATOR_JOB_RECORD
        );
    }
}
