/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.translator.database.jooq;


import eu.dissco.core.translator.database.jooq.tables.DataMapping;
import eu.dissco.core.translator.database.jooq.tables.SourceSystem;
import eu.dissco.core.translator.database.jooq.tables.TranslatorJobRecord;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.data_mapping</code>.
     */
    public static final DataMapping DATA_MAPPING = DataMapping.DATA_MAPPING;

    /**
     * The table <code>public.source_system</code>.
     */
    public static final SourceSystem SOURCE_SYSTEM = SourceSystem.SOURCE_SYSTEM;

    /**
     * The table <code>public.translator_job_record</code>.
     */
    public static final TranslatorJobRecord TRANSLATOR_JOB_RECORD = TranslatorJobRecord.TRANSLATOR_JOB_RECORD;
}
