/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.translator.database.jooq.tables;


import eu.dissco.core.translator.database.jooq.Keys;
import eu.dissco.core.translator.database.jooq.Public;
import eu.dissco.core.translator.database.jooq.tables.records.DataMappingRecord;

import java.time.Instant;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataMapping extends TableImpl<DataMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_mapping</code>
     */
    public static final DataMapping DATA_MAPPING = new DataMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataMappingRecord> getRecordType() {
        return DataMappingRecord.class;
    }

    /**
     * The column <code>public.data_mapping.id</code>.
     */
    public final TableField<DataMappingRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.version</code>.
     */
    public final TableField<DataMappingRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.name</code>.
     */
    public final TableField<DataMappingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.date_created</code>.
     */
    public final TableField<DataMappingRecord, Instant> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.date_modified</code>.
     */
    public final TableField<DataMappingRecord, Instant> DATE_MODIFIED = createField(DSL.name("date_modified"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.date_tombstoned</code>.
     */
    public final TableField<DataMappingRecord, Instant> DATE_TOMBSTONED = createField(DSL.name("date_tombstoned"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.data_mapping.creator</code>.
     */
    public final TableField<DataMappingRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.mapping_data_standard</code>.
     */
    public final TableField<DataMappingRecord, String> MAPPING_DATA_STANDARD = createField(DSL.name("mapping_data_standard"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.data_mapping.data</code>.
     */
    public final TableField<DataMappingRecord, JSONB> DATA = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    private DataMapping(Name alias, Table<DataMappingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataMapping(Name alias, Table<DataMappingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_mapping</code> table reference
     */
    public DataMapping(String alias) {
        this(DSL.name(alias), DATA_MAPPING);
    }

    /**
     * Create an aliased <code>public.data_mapping</code> table reference
     */
    public DataMapping(Name alias) {
        this(alias, DATA_MAPPING);
    }

    /**
     * Create a <code>public.data_mapping</code> table reference
     */
    public DataMapping() {
        this(DSL.name("data_mapping"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DataMappingRecord> getPrimaryKey() {
        return Keys.DATA_MAPPING_PK;
    }

    @Override
    public DataMapping as(String alias) {
        return new DataMapping(DSL.name(alias), this);
    }

    @Override
    public DataMapping as(Name alias) {
        return new DataMapping(alias, this);
    }

    @Override
    public DataMapping as(Table<?> alias) {
        return new DataMapping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataMapping rename(String name) {
        return new DataMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataMapping rename(Name name) {
        return new DataMapping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataMapping rename(Table<?> name) {
        return new DataMapping(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping where(Condition condition) {
        return new DataMapping(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataMapping where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataMapping where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataMapping where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataMapping where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataMapping whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
